swapi:
    baseUrl: "https://swapi.dev/api/"
spring:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    datasource:
        url: jdbc:h2:mem:/data/testdb
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false

